import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Provider from "@/app/provider";
import Header from "@/components/Header/Header";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="mx-auto max-w-4xl p-4 flex flex-col min-h-screen">
          <Provider>
            <Toaster/>
            <Header />
            {children}
            <Footer />
          </Provider>
        </main>
      </body>
    </html>
  );
}
